language: node_js
node_js:
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - node
os:
  - linux
  - osx
install:
  npm install
script:
  - npm run lint
  - npm run test:single
  - npm run test:subdomain
